### ISSUE TITLE
casting intrinsics

### ISSUE THREAD

**Issue by jackmott** [BurntSushi/stdsimd#7]
`_mm256_castpd_ps`

"Cast vector of type __m256d to type __m256. This intrinsic is only used for compilation and does not generate any instructions, thus it has zero latency."

signature is:
`pub fn _mm256_castpd_ps(a: f64x4) -> f32x8`

How to perform the cast properly? `simd_cast` doesn't like that one is of length 4 and the other is of length 8

**Comment by BurntSushi** [comment]
The docs in Clang's header say this:

```
/* Cast between vector types */
/// \brief Casts a 256-bit floating-point vector of [4 x double] into a 256-bit
///    floating-point vector of [8 x float].
///
/// \headerfile <x86intrin.h>
///
/// This intrinsic has no corresponding instruction.
///
/// \param __a
///    A 256-bit floating-point vector of [4 x double].
/// \returns A 256-bit floating-point vector of [8 x float] containing the same
///    bitwise pattern as the parameter.
```

In particular, this part:

```
/// \returns A 256-bit floating-point vector of [8 x float] containing the same
///    bitwise pattern as the parameter.
```

to me implies that this should be a transmute, i.e., a bitcast. Indeed, this [page](https://software.intel.com/en-us/node/695301) from Intel's C++ compiler docs seems to confirm that. This seems to be true of the other cast vendor intrinsics as well.

**Comment by BurntSushi** [comment]
`simd_cast` would actually be the wrong implementation here, since that might generate instructions to convert the bitwise representation such that the values remain equal.

**Comment by BurntSushi** [comment]
Closing this out to clean up the issue tracker. If there are any lingering questions, please open a new issue. :-)
